### ISSUE TITLE
configuration guide link for server install 404s

### ISSUE THREAD

**Issue by jabowery** [vocascan/documentation#1]
"For more details about the environment variables see c[onfiguration guide](https://docs.vocascan.com/#/configuration)."

404s

**Comment by noctera** [comment]
Unfortunately, the link to the subpage has not been updated. We will fix it asap. In the meantime you can go to the page under "Configuration" via the menu, or use this link here. 

https://docs.vocascan.com/#/vocascan-server/configuration

 Thank you for notifying us.

**Comment by noctera** [comment]
The Issue should be solved now. If you don't mind I'll close it. 

If you find further problems you are welcome to open a new Issue.
